// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: create_post.sql

package database

import (
	"context"
	"time"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts
    (title, url, description, feed_id, published_at, created_at, updated_at)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
       ) RETURNING id, title, url, description, feed_id, published_at, created_at, updated_at
`

type CreatePostParams struct {
	Title       string
	Url         string
	Description string
	FeedID      int32
	PublishedAt time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.FeedID,
		arg.PublishedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
