// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds_with_user.sql

package database

import (
	"context"
	"database/sql"
)

const feedsWithUsers = `-- name: FeedsWithUsers :many

SELECT
    feeds.name,
    feeds.url,
    users.name as username
FROM feeds
    LEFT JOIN users
        ON feeds.user_id = users.id
`

type FeedsWithUsersRow struct {
	Name     string
	Url      string
	Username sql.NullString
}

func (q *Queries) FeedsWithUsers(ctx context.Context) ([]FeedsWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, feedsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedsWithUsersRow
	for rows.Next() {
		var i FeedsWithUsersRow
		if err := rows.Scan(&i.Name, &i.Url, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
