// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mark_feed_as_fetched.sql

package database

import (
	"context"
	"time"
)

const markFeedAsFetched = `-- name: MarkFeedAsFetched :exec
UPDATE feeds
SET updated_at = $2, last_fetched_at = $2 where id = $1
`

type MarkFeedAsFetchedParams struct {
	ID        int32
	UpdatedAt time.Time
}

func (q *Queries) MarkFeedAsFetched(ctx context.Context, arg MarkFeedAsFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markFeedAsFetched, arg.ID, arg.UpdatedAt)
	return err
}
